CREATE DATABASE IF NOT EXISTS DB_NYTIMES
   CHARACTER SET utf8;

USE DB_NYTIMES;

CREATE TABLE TERM (
   TERM_ID INT(11) NOT NULL AUTO_INCREMENT,
   TERM VARCHAR(100) NOT NULL,
   PRIMARY KEY (TERM_ID),
   KEY (TERM)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE CATEGORY (
   CAT_ID INT(11) NOT NULL AUTO_INCREMENT,
   CAT_NAME VARCHAR(100) NOT NULL,
   PRIMARY KEY (CAT_ID)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE DOCUMENT (
   DOC_ID INT(11) NOT NULL AUTO_INCREMENT,
   DOC_DATE DATE NOT NULL,
   CAT_ID INT(11) NOT NULL REFERENCES CATEGORY (CAT_ID),
   URL VARCHAR(200) NOT NULL,
   PRIMARY KEY (DOC_ID),
   KEY (DOC_DATE)   
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE TERM_TF (
   TERM_ID INT(11) NOT NULL REFERENCES TERM (TERM_ID),
   DOC_ID INT(11) NOT NULL REFERENCES DOCUMENT (DOC_ID),
   TF INT(11) NOT NULL,
   TF_NORM DECIMAL (18, 16) NOT NULL,
   PRIMARY KEY (TERM_ID, DOC_ID),
   KEY (DOC_ID)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE TFIDF_INTERVAL (
	INTERVAL_ID INT(11) NOT NULL AUTO_INCREMENT,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    DOC_COUNT INT(11) NOT NULL,
    PRIMARY KEY (INTERVAL_ID)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE TFIDF_INTERVAL_CAT (
	INTERVAL_ID INT(11) NOT NULL AUTO_INCREMENT,
    CAT_ID INT(11) NOT NULL REFERENCES CATEGORY (CAT_ID),
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    DOC_COUNT INT(11) NOT NULL,
    PRIMARY KEY (INTERVAL_ID, CAT_ID)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE TERM_TF_INTERVAL (
	INTERVAL_ID INT(11) NOT NULL REFERENCES TFIDF_INTERVAL (INTERVAL_ID),
    TERM_ID INT(11) NOT NULL REFERENCES TERM (TERM_ID),
    TF INT(11) NOT NULL,
    TERM_DOC_COUNT INT(11) NOT NULL,
    TF_IDF DECIMAL (24, 16) NOT NULL,
    PRIMARY KEY (INTERVAL_ID, TERM_ID)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE TERM_TF_INTERVAL_CAT (
	INTERVAL_ID INT(11) NOT NULL REFERENCES TFIDF_INTERVAL_CAT (INTERVAL_ID),
    CAT_ID INT(11) NOT NULL REFERENCES TFIDF_INTERVAL_CAT (CAT_ID),
    TERM_ID INT(11) NOT NULL REFERENCES TERM (TERM_ID),
    TF INT(11) NOT NULL,
    TERM_DOC_COUNT INT(11) NOT NULL,
    TF_IDF DECIMAL (24, 16) NOT NULL,
    PRIMARY KEY (INTERVAL_ID, CAT_ID, TERM_ID)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE BANNED_TERMS (
   TERM_ID INT(11) NOT NULL REFERENCES TERM (TERM_ID),
   PRIMARY KEY (TERM_ID)
) ENGINE=INNODB DEFAULT CHARSET=utf8;